// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",      
  options: {
    checkForUpdate: false
  },
  handlers: [
    {
      match: /^https:\/\/ui\.adsabs\.harvard\.edu\/.*$/,
      browser: "Brave Browser"
    },
    {
      match: /^https:\/\/arxiv\.org\/.*$/,
      browser: "Brave Browser"
    }
  ]
}
