python-preference = 'managed'

# https://github.com/astral-sh/uv/issues/8587
index-strategy = "unsafe-best-match"

[[index]]
url = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/"
default = false
